#!/usr/bin/env node
/*
 * Generates styles/tokens.css - the Monokai Pro design-token ramps for Inkdrop v6.
 *
 *   npm run tokens
 *
 * Why a generator: tokens.css is ~380 declarations. Hand-editing it makes a wrong
 * step invisible. Change the palette in scripts/lib/palette.mjs and regenerate.
 *
 * How it works: Inkdrop's built-in tokens.css defines every ramp twice -
 *   --hsl-<family>-<step>:   <H>deg <S>% <L>%      (bare triplet, for hsl(... / alpha))
 *   --color-<family>-<step>: hsl(var(--hsl-...))   (resolved color)
 * We redefine both in @layer theme, which sits above @layer tokens, so every one
 * of the ~890 semantic UI variables that resolves through a ramp picks up Monokai
 * without being named here. See https://github.com/inkdropapp/css
 *
 * Each accent family holds the anchor's hue and saturation and interpolates
 * lightness across the 11 steps, anchored so step 500 IS the Monokai color.
 * The sibling families (rose/pink, amber, lime/emerald, teal/sky, indigo/purple)
 * are the anchor nudged in hue, so components that reach for a neighbouring
 * family stay inside the Monokai range instead of falling back to Tailwind.
 *
 * The file is written in place rather than piped: `node gen-tokens.mjs > tokens.css`
 * truncates the target before this script runs, so a palette that fails to parse
 * would leave an empty stylesheet behind.
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { hexToHsl, hexToRgb, rgbToHex, triplet } from './lib/color.mjs'
import { ACCENTS, NEUTRAL, NEUTRAL_ALIASES, STEPS } from './lib/palette.mjs'
import { root } from './lib/theme.mjs'

// Lightness is interpolated as a FRACTION of the distance from the anchor
// (step 500) to a ceiling/floor - not as a fixed offset. Fixed offsets collapse
// at the ends: Monokai's purple already sits at L 78%, so +28/+25/+19 all clamp
// to the ceiling and steps 50/100/200 come out identical. Fractions keep the
// ramp monotonic whatever the anchor's lightness.
const L_CEILING = 97
const L_FLOOR = 12
// Toward the ceiling. 400 is deliberately close to the anchor: Inkdrop's
// dark-mode defaults reach for -400 as often as -500, and both should read as
// the Monokai color rather than a washed-out tint of it.
const L_UP = { 400: 0.17, 300: 0.42, 200: 0.66, 100: 0.85, 50: 0.96 }
// Toward the floor.
const L_DOWN = { 600: 0.18, 700: 0.35, 800: 0.52, 900: 0.66, 950: 0.86 }

// Saturation multiplier per step. Monokai's accents sit at 70-100% saturation,
// which stays pleasant around the anchor but turns lurid once lightness drops:
// 100% saturation at L 19% is a signal-flare red, not a Monokai red. Taper it
// at both ends the way Tailwind's ramps do.
const S_SCALE = {
  50: 0.9,
  100: 0.92,
  200: 0.95,
  300: 0.98,
  400: 1,
  500: 1,
  600: 0.97,
  700: 0.9,
  800: 0.82,
  900: 0.74,
  950: 0.62,
}

// --- ramp construction -------------------------------------------------------

function accentRamp(anchorHex, hueShift) {
  const anchor = hexToHsl(anchorHex)
  const out = {}
  for (const step of STEPS) {
    let l = anchor.l
    if (step in L_UP) l = anchor.l + (L_CEILING - anchor.l) * L_UP[step]
    else if (step in L_DOWN) l = anchor.l - (anchor.l - L_FLOOR) * L_DOWN[step]
    out[step] = triplet({
      h: anchor.h + hueShift,
      s: anchor.s * S_SCALE[step],
      l,
    })
  }
  return out
}

function neutralRamp() {
  const filled = { ...NEUTRAL }
  // Fill 100/200/300 by interpolating in RGB, NOT HSL. #FCFCFA reports 25%
  // saturation at 60deg, but that is a 2/255 rounding artefact, not a real
  // warmth; carrying it down an HSL ramp turns the light greys visibly pink.
  // Averaging two near-greys in RGB cannot invent a hue.
  const lo = hexToRgb(NEUTRAL[50]).slice(0, 3)
  const hi = hexToRgb(NEUTRAL[400]).slice(0, 3)
  const FILL = { 100: 0.22, 200: 0.48, 300: 0.73 }
  for (const [step, t] of Object.entries(FILL)) {
    filled[step] = rgbToHex(lo.map((c, i) => c + (hi[i] - c) * t))
  }
  const out = {}
  for (const step of STEPS) out[step] = triplet(hexToHsl(filled[step]))
  return out
}

// --- emit --------------------------------------------------------------------

const families = { neutral: neutralRamp() }
for (const [name, [hex, shift]] of Object.entries(ACCENTS)) {
  families[name] = accentRamp(hex, shift)
}
for (const name of NEUTRAL_ALIASES) {
  families[name] = { ...families.neutral }
}

const HEADER = `  /*
   * Monokai Pro Dark - design-token ramps.
   *
   * GENERATED by scripts/gen-tokens.mjs - do not edit by hand.
   * Edit scripts/lib/palette.mjs and run \`npm run tokens\`.
   *
   * Overrides the built-in --hsl-* / --color-* ramps so every component that
   * resolves through a design token picks up Monokai without being named
   * individually. Each accent family anchors a Monokai color at step 500.
   */`

const RESOLVED_NOTE = `    /* Resolved colors. Redundant in principle - --color-* is defined as
       hsl(var(--hsl-*)) upstream and would follow the overrides above - but
       the official themes restate them, and generate-palette snapshots
       resolved values, so keep the pair explicit. */`

const block = lines => lines.join('\n')

const hslBlocks = Object.entries(families).map(([name, ramp]) =>
  block([`    /* ${name} */`, ...STEPS.map(step => `    --hsl-${name}-${step}: ${ramp[step]};`)]),
)

const colorBlocks = Object.keys(families).map(name =>
  block(STEPS.map(step => `    --color-${name}-${step}: hsl(var(--hsl-${name}-${step}));`)),
)

const css = block([
  '@layer theme {',
  HEADER,
  '  :root {',
  hslBlocks.join('\n\n'),
  '',
  RESOLVED_NOTE,
  '',
  colorBlocks.join('\n\n'),
  '  }',
  '}',
])

writeFileSync(join(root, 'styles', 'tokens.css'), css + '\n')
